project:
  name: cfn-ci-cd
  regions:
  - us-east-1
tests:
  vpc-defaults:
    template: ./templates/create_ec2.yaml
    regions:
    - us-east-1
    parameters:
      NameOfService: "Managed by CF"
      KeyName: "django_eb_app"